import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export async function POST(request) {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: "Missing RESEND_API_KEY in environment" }, { status: 500 });
  }

  const resend = new Resend(apiKey);

  try {
    const { parentName, parentEmail, childName, phone, childAge, programInterest } = await request.json();

    const { data, error } = await resend.emails.send({
      from: 'Leads(LittleOaks) <onboarding@resend.dev>', // Update this with your verified domain if available
      to: ['littleoaksbhubaneswar@gmail.com'], // The email address you want to receive the inquiries
      subject: `New Admission Inquiry - ${parentName}`,
      html: `
        <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #f9f9f9; padding: 20px; border-radius: 8px; border: 1px solid #e0e0e0;">
          <div style="text-align: center; margin-bottom: 20px;">
            <h1 style="color: #2c3e50; margin: 0;">New Admission Inquiry</h1>
            <p style="color: #7f8c8d; font-size: 14px; margin-top: 5px;">You have a new inquiry from the website</p>
          </div>
          <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #7f8c8d; width: 40%;"><strong>Parent's Name:</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #2c3e50;">${parentName}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #7f8c8d;"><strong>Email Address:</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #2c3e50;"><a href="mailto:${parentEmail}" style="color: #3498db; text-decoration: none;">${parentEmail}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #7f8c8d;"><strong>Child's Name:</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #2c3e50;">${childName}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #7f8c8d;"><strong>Phone Number:</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #2c3e50;"><a href="tel:${phone}" style="color: #3498db; text-decoration: none;">${phone}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #7f8c8d;"><strong>Child's Age:</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #2c3e50;">${childAge} Years</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #7f8c8d;"><strong>Program Interest:</strong></td>
                <td style="padding: 10px 0; color: #2c3e50;">${programInterest}</td>
              </tr>
            </table>
          </div>
          <div style="text-align: center; margin-top: 20px; color: #bdc3c7; font-size: 12px;">
            <p>This email was automatically generated by Little Oaks Admissions Form.</p>
            <p style="margin-top: 10px;">Developed by <a href="https://brandnestagency.vercel.app/" target="_blank" style="color: #3498db; text-decoration: none;">Brandnest</a> - India's First AI Powered Web & Digital Marketing Agency</p>
          </div>
        </div>
      `,
    });

    if (error) {
      console.error('Resend Admin Error:', error);
      return NextResponse.json({ error }, { status: 400 });
    }

    // Auto-responder to the client (parent)
    // Wrapped in try-catch so if it fails (due to unverified domain), the main request still succeeds
    try {
      await resend.emails.send({
        from: 'Little Oaks Admissions <onboarding@resend.dev>', // Update to your domain email later (e.g. info@littleoaks.com)
        to: [parentEmail],
        subject: `Thank you for your inquiry, ${parentName}!`,
        html: `
          <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 30px; border-radius: 12px; border: 1px solid #f0f0f0; box-shadow: 0 4px 6px rgba(0,0,0,0.02);">
            <div style="text-align: center; margin-bottom: 30px;">
              <h1 style="color: #ff6b6b; margin: 0; font-size: 28px;">LITTLE OAKS</h1>
              <p style="color: #f1c40f; font-weight: bold; font-size: 14px; margin-top: 5px; letter-spacing: 2px;">★ PRE SCHOOL ★</p>
            </div>
            
            <h2 style="color: #2c3e50; font-size: 20px;">Dear ${parentName},</h2>
            <p style="color: #34495e; line-height: 1.6; font-size: 16px;">
              Thank you for considering <strong>Little Oaks Pre School</strong> for ${childName}'s early education. We have successfully received your inquiry for the <strong>${programInterest.replace('-', ' ').toUpperCase()}</strong> program.
            </p>
            <p style="color: #34495e; line-height: 1.6; font-size: 16px;">
              Our admissions team is currently reviewing your details and will get back to you shortly at <strong>${phone}</strong> to schedule a campus visit or discuss the next steps.
            </p>
            
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 30px 0; text-align: center;">
              <h3 style="color: #2c3e50; margin-top: 0;">Have immediate questions?</h3>
              <p style="color: #7f8c8d; margin-bottom: 0;">Call us directly at <a href="tel:+918093052861" style="color: #3498db; text-decoration: none; font-weight: bold;">+91 8093052861</a></p>
            </div>
            
            <p style="color: #34495e; line-height: 1.6; font-size: 16px;">
              Warm regards,<br/>
              <strong>Admissions Team</strong><br/>
              Little Oaks Pre School
            </p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;" />
            
            <div style="text-align: center; color: #bdc3c7; font-size: 12px;">
              <p>Campus Address: Patrapada, Bhubaneswar, Odisha - 751019</p>
              <p style="margin-top: 15px;">
                Developed by <a href="https://brandnestagency.vercel.app/" target="_blank" style="color: #3498db; text-decoration: none;">Brandnest</a> - India's First AI Powered Web & Digital Marketing Agency
              </p>
            </div>
          </div>
        `,
      });
    } catch (autoResponderError) {
      console.error('Auto-responder failed (likely domain not verified yet):', autoResponderError);
      // We don't throw an error here because the main admin email was successful
    }

    return NextResponse.json({ message: 'Email sent successfully', data }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
